sudo: required
dist: trusty
language: node_js
node_js:
  - '13.5.0'
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  - npm run lint
  - npm run solium
  - npm test
before_script:
  - ganache-cli > /dev/null &
  - sleep 5
# after_script:
#   - npm run coverage && cat coverage/lcov.info | coveralls

